-- RevWorkforce Database Schema (Oracle SQL)

-- Departments table
CREATE TABLE department (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(100) NOT NULL
);

-- Users table (Authentication)
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL, -- ROLE_EMPLOYEE, ROLE_MANAGER, ROLE_ADMIN
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Employee table
CREATE TABLE employee (
    emp_id VARCHAR2(20) PRIMARY KEY, -- Corporate ID like RW001
    user_id NUMBER UNIQUE REFERENCES users(user_id),
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    phone VARCHAR2(20),
    address VARCHAR2(255),
    emergency_contact VARCHAR2(100),
    dob DATE,
    joining_date DATE NOT NULL,
    department_id NUMBER REFERENCES department(department_id),
    designation VARCHAR2(100),
    manager_id VARCHAR2(20) REFERENCES employee(emp_id),
    salary NUMBER(10, 2),
    ssId VARCHAR2(20) -- Social Security or similar ID
);

-- Leave Types
CREATE TABLE leave_type (
    leave_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_name VARCHAR2(50) NOT NULL,
    max_per_year NUMBER NOT NULL
);

-- Leave Balances
CREATE TABLE leave_balance (
    balance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id VARCHAR2(20) REFERENCES employee(emp_id),
    leave_type_id NUMBER REFERENCES leave_type(leave_type_id),
    balance_days NUMBER NOT NULL,
    UNIQUE(emp_id, leave_type_id)
);

-- Leave Applications
CREATE TABLE leave_application (
    leave_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id VARCHAR2(20) REFERENCES employee(emp_id),
    leave_type_id NUMBER REFERENCES leave_type(leave_type_id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR2(255),
    status VARCHAR2(20) DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED, CANCELLED
    applied_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_by VARCHAR2(20) REFERENCES employee(emp_id),
    manager_comment VARCHAR2(255)
);

-- Performance Reviews
CREATE TABLE performance_review (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id VARCHAR2(20) REFERENCES employee(emp_id),
    review_year NUMBER NOT NULL,
    achievements CLOB,
    improvements CLOB,
    self_rating NUMBER(2,1),
    manager_rating NUMBER(2,1),
    manager_feedback CLOB,
    status VARCHAR2(20) DEFAULT 'SUBMITTED' -- SUBMITTED, REVIEWED
);

-- Goals
CREATE TABLE goals (
    goal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id VARCHAR2(20) REFERENCES employee(emp_id),
    goal_desc VARCHAR2(500) NOT NULL,
    deadline DATE,
    priority VARCHAR2(10) DEFAULT 'MEDIUM', -- HIGH, MEDIUM, LOW
    success_metric VARCHAR2(255),
    progress NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'NOT_STARTED'
);

-- Holiday Calendar
CREATE TABLE holiday_calendar (
    holiday_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE NOT NULL,
    description VARCHAR2(100) NOT NULL
);

-- Announcements
CREATE TABLE announcements (
    announcement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    message CLOB NOT NULL,
    created_by VARCHAR2(20) REFERENCES employee(emp_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Notifications
CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(user_id),
    message VARCHAR2(500) NOT NULL,
    type VARCHAR2(50),
    is_read NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Events (Generic log for milestones/events)
CREATE TABLE app_events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id VARCHAR2(20) REFERENCES employee(emp_id),
    event_type VARCHAR2(50),
    event_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
